name: Update Instagram Followers

on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  update_followers:
    runs-on: ubuntu-latest  # Use Linux runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install ChromeDriver
        run: |
          wget "https://storage.googleapis.com/chrome-for-testing-public/134.0.6998.88/linux64/chromedriver-linux64.zip"
          unzip chromedriver-linux64.zip
          sudo mv chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: pip install selenium

      - name: Run Python Script
        run: python update_followers.py

      - name: Commit and Push Updated Followers
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add followers.json
          git commit -m "Updated followers count" || exit 0
          git push
