name: Update Instagram Followers

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 10 minutes

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests beautifulsoup4

      - name: Run Script
        run: python update_followers.py

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add followers.json
          git commit -m "Update followers count" || exit 0
          git push
