name: Update Instagram Followers

on:
  schedule:
    - cron: '0 12 * * *'  # Runs daily at 12:00 UTC
  workflow_dispatch:  # Allows manual trigger

env:
  CHROMEDRIVER_PATH: "chromedriver.exe"
  USERNAME: "lifeatsendcloud"

jobs:
  fetch-followers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Download ChromeDriver
        run: |
          sudo apt update
          sudo apt install -y chromium-chromedriver

      - name: Run script to fetch followers
        run: python update_followers.py

      - name: Commit and push updated followers count
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add followers_count.txt
          git commit -m 'Updated followers count' || echo "No changes to commit"
          git push
